/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.trantorinc.wellnesstracker.controller;

import com.trantorinc.wellnesstracker.model.Report;
import com.trantorinc.wellnesstracker.model.ReportsPostRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-01-15T17:46:27.736648+05:30[Asia/Kolkata]")
@Validated
@Tag(name = "reports", description = "the reports API")
public interface ReportsApi {

    /**
     * POST /reports : Generate a new wellness report
     *
     * @param reportsPostRequest  (required)
     * @return Report generated (status code 201)
     *         or Invalid request parameters (status code 400)
     */
    @Operation(
        operationId = "reportsPost",
        summary = "Generate a new wellness report",
        responses = {
            @ApiResponse(responseCode = "201", description = "Report generated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Report.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request parameters")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/reports",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default Mono<ResponseEntity<Report>> reportsPost(
        @Parameter(name = "ReportsPostRequest", description = "", required = true) @Valid @RequestBody Mono<ReportsPostRequest> reportsPostRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"reportId\" : \"reportId\", \"data\" : { \"totalSteps\" : 0, \"averageWaterIntake\" : 1, \"averageSleepHours\" : 6 }, \"departmentId\" : \"departmentId\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(reportsPostRequest).then(Mono.empty());

    }

}
